name: Nilson
title: Nilsonlinux Web
description: Nilsonlinux. Desenvolvedor de soluções com automação inteligente. Zabbix, Grafana, Jira, Bots, Shellscript e outros.
url: https://nilsonlinux.github.io/
author: Nilsonlinux
github: https://github.com/nilsonlinux/Nilsonlinux
twitter: Nilsonlinux

encoding: utf-8
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
